### ISSUE TITLE
IPN

### ISSUE THREAD

**Issue by bryan954** [AngelVega22/izipay-nodejs-paymentForm#1]
El servidor del comercio debe estar expuesto de manera pública para que la IPN pueda responder. En caso de que el servidor sea local, ingreso o limitación de usuarios por VPN, algún firewall, CSRF_TOKEN, etc. No podrá comunicarse la respuesta, de igual forma la IPN solo envía la respuesta por método post a una URL estática que proporcionará el comercio.
Si en caso no es posible habilitar de manera pública el servidor o dependa de algún uso de autenticación. Entonces se deberá colocar la IP del servidor de la IPN en una lista blanca manejada por el servidor del comercio.

**Comment by AngelVega22** [comment]
Muchas gracias, ya corregí el README.
